apiVersion: v1
kind: Service
metadata:
  name: jenkins-slave-service
  namespace: jenkins
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-slave-server
  type: LoadBalancer 
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
